name: ConsoleScheduler
main: BoomerBR.plugin.ConsoleScheduler
version: 1.4.3
author: BoomerBR

commands:
  csc:
    aliases: [cscheduler]
    description: ConsoleScheduler Commands
    usage: /csc
    
permissions:
   ConsoleScheduler.use:
     description: Use the plugin.
     default: op
